### ISSUE TITLE
External storage support for Google Drive don't work

### ISSUE THREAD

**Issue by sergesr** [NastuzziSamy/files_external_gdrive#13]
I have installed External storage support for Google Drive	0.2.8 on my nexcloud R13.
The signal indicates green ok on my external storage.
no file is displayed in the list.

I have un other server Onwclous with a similar plugin, external Google drive, it work fine
Thanks for your help.

Serge

**Comment by NastuzziSamy** [comment]
Hi @sergesr,

Can you give more information ?
Like your logs so I can check that there is a problem

**Comment by sergesr** [comment]
Hi,

**Comment by sergesr** [comment]
Hi,
the log after trying to obtain google drive files,
thank's

[nextcloud.zip](https://github.com/NastuzziSamy/files_external_gdrive/files/2063094/nextcloud.zip)

**Comment by sergesr** [comment]
I have this in my log:


Debug | PHP | disk_free_space():  Value too large for defined data type at  /home/roumsfryrh/www/nextcloud/lib/private/Files/Storage/Local.php#298
-- | -- | --

**Comment by NastuzziSamy** [comment]
I think it is the same error for everyone.

Do you have large files or a lot of files and directories ?

**Comment by sergesr** [comment]
not so may directories, but a directory google photos synced, with many file

**Comment by NastuzziSamy** [comment]
I think it is fixed
