### ISSUE TITLE
2 issues on fresh install

### ISSUE THREAD

**Issue by GodAtum360** [NastuzziSamy/files_external_gdrive#14]
When click grant access

`GET http://10.0.0.133/apps/files_external_gdrive/js/gdrive.js?v=00aee314-0 404 (Not Found)`
and
`oauth2.js?v=00aee314-0:87 Uncaught TypeError: Cannot read property 'message' of undefined
    at Object.success (oauth2.js?v=00aee314-0:87)
    at j (core.js?v=00aee314-0:2)
    at Object.fireWith [as resolveWith] (core.js?v=00aee314-0:2)
    at x (core.js?v=00aee314-0:4)
    at XMLHttpRequest.<anonymous> (core.js?v=00aee314-0:4)`

**Comment by NastuzziSamy** [comment]
Hey, is the app installed in a custom directory ?

**Comment by NastuzziSamy** [comment]
@ChristopherM87

**Comment by OzymandiasTheGreat** [comment]
I'm getting the same errors. I did install from the snap which I guess is causing this.

**Comment by NastuzziSamy** [comment]
Closing this issue, guideline on README now.

Open a new issue if it fails again
