### ISSUE TITLE
External storage support for Google Drive don't work 

### ISSUE THREAD

**Issue by sergesr** [NastuzziSamy/files_external_gdrive#15]
I have installed External storage support for Google Drive	0.2.8 on my nexcloud R13.
The signal indicates green ok on my external storage.
no file is displayed in the list.

I have un other server Onwclous with a similar plugin, external Google drive, it work fine

I have this on log:

Debug | PHP | disk_free_space(): Value too large for defined data type at /home/roumsfryrh/www/nextcloud/lib/private/Files/Storage/Local.php#298 | 2018-06-06T19:40:29+0200
-- | -- | -- | --
Debug | PHP | disk_free_space(): Value too large for defined data type at /home/roumsfryrh/www/nextcloud/lib/private/Files/Storage/Local.php#298 | 2018-06-06T19:40:06+0200
Debug | PHP | disk_free_space(): Value too large for defined data type at /home/roumsfryrh/www/nextcloud/lib/private/Files/Storage/Local.php#298 | 2018-06-06T19:40:06+0200

Thanks for your help.

Serge

**Comment by NastuzziSamy** [comment]
https://github.com/NastuzziSamy/files_external_gdrive/issues/13
