### ISSUE TITLE
oauth not complete

### ISSUE THREAD

**Issue by ferdiga** [NastuzziSamy/files_external_gdrive#16]
Nextcloud 13.0.2
files_external_gdrive 0.2.8
I had to set 
Authorised redirect URIs to
https://service.dddd.dd/mycloud/index.php/settings/personal/ https://service.dddd.dd/mycloud/index.php/settings/admin/ https://service.dddd.dd/mycloud/index.php/settings/externalstorages/ https://service.dddd.dd/mycloud/index.php/settings/admin/externalstorages
now the External storage is green but status still "Grant access" but not clickable
I'have got the mail confirming that nextcloud can access google drive.
in nextcloud 
* I see the configured mount mount - size =pending
* if I open the folder - no files are there 

the log file shows:

{"reqId":"gJwftsqjhB12VNPFz8H0","level":3,"time":"2018-06-09T17:21:10+00:00","remoteAddr":"111.111.111.111","user":"myself","app":"files_external","method":"GET","url":"\/nextcloud\/index.php\/apps\/files_external\/userglobalstorages\/11?testOnly=false","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"**Unknown storage backend \\\"googledrive\\\"**\",\"Code\":1,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/lib\\\/config.php(240): OC\\\\Files\\\\Storage\\\\FailedStorage->setAvailability(false)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(256): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, false, false)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/UserGlobalStoragesController.php(121): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_External\\\\Lib\\\\StorageConfig), false)\\n#3 [internal function]: OCA\\\\Files_External\\\\Controller\\\\UserGlobalStoragesController->show(11, false)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\UserGlobalStoragesController), 'show')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\UserGlobalStoragesController), 'show')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Files_Exter...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/index.php(37): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/FailedStorage.php\",\"Line\":213,\"Hint\":\"Storage is temporarily not available\"}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/66.0.3359.181 Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}

**Comment by ferdiga** [comment]
rgrep googledrive *  in apps directory
returns only this line
files_external_gdrive/vendor/nao-pon/flysystem-google-drive/README.md:    'rootCssClass' => 'elfinder-navbar-root-googledrive'

**Comment by NastuzziSamy** [comment]
I dont understand from where it is caused.

Did you use Google Drive files external from Nextcloud 12 ? 

Does it work now ?

**Comment by ferdiga** [comment]
I used the one form github (here)

**Comment by NastuzziSamy** [comment]
Did you run the makefile ?

**Comment by ferdiga** [comment]
even after make I get the error mentioned above 
Unknown storage backend \"googledrive\"

**Comment by ferdiga** [comment]
![image](https://user-images.githubusercontent.com/6248560/41331456-600404f6-6ed9-11e8-852d-4b733f564d4b.png)

shouldn't it say "Access granted"?

**Comment by NastuzziSamy** [comment]
Issue reported: https://github.com/nextcloud/server/issues/14646

Closing this issue
