### ISSUE TITLE
Gdrive issue, seems to authenticate but still red

### ISSUE THREAD

**Issue by benderstwin** [NastuzziSamy/files_external_gdrive#19]
I went through the docs to enable the authentication in google.  I use the id and secret, click grant access, it pops up with my account and I click "allow".  It returns me to Nextcloud and looks like all is good except the red square is still there.  I can't open the folder.  What could I check?

**Comment by NastuzziSamy** [comment]
Hi @benderstwin , check the doc, it is up to date now
