### ISSUE TITLE
gdrive.js does not load when installed in a custom app directory

### ISSUE THREAD

**Issue by simonbru** [NastuzziSamy/files_external_gdrive#2]
[Nextcloud documentation](https://docs.nextcloud.com/server/13/admin_manual/installation/apps_management_installation.html#using-custom-app-directories) recommends using a second, writable directory for apps installed by users. The Nextcloud docker image automatically configures the `custom_apps` for this purpose.
However in my case `gdrive.js` does not load when `files_external_gdrive` is installed in `custom_apps`. The server returns a weird 302 redirect for gdrive.js when opening `/settings/admin/externalstorages` in the browser, and Nextcloud logs the following:

`Debug | files_external | Could not find resource file "/apps/files_external/js/../../files_external_gdrive/js/gdrive.js"`

Copying `files_external_gdrive` into the apps folder temporarily works around the issue (which is fine for a one time setup).

I guess this is more an issue of `files_external_gdrive` being in a different apps folder than `files_external`. I noticed the exact same issue with [files_external_dropbox](https://github.com/icewind1991/files_external_dropbox).

**Nextcloud version:** 13.0.2 using the [13.0-apache docker image](https://hub.docker.com/_/nextcloud/)

**Comment by NastuzziSamy** [comment]
Hi again,

Could you try this https://github.com/NastuzziSamy/files_external_gdrive/tree/patch%232 and tell me if it resolves something ?

Thanks

**Comment by simonbru** [comment]
Hi, this patch does not seem to fix the issue, I now get the following error:
`Could not find resource file "/apps/files_external/js//files_external_gdrive/js/gdrive.js"`

Thanks for your work and reactivity !

**Comment by simonbru** [comment]
I found a solution that seems to work when the app is in any folder. However I don't know how correct or clean it is.
https://github.com/simonbru/files_external_gdrive/commit/4151baeca448197130d6afdc80a12eadb499530f

**Comment by NastuzziSamy** [comment]
Hi @simonbru, I think it cant be cleaner.

Do not hesitate to PR ;)

**Comment by simonbru** [comment]
Done https://github.com/NastuzziSamy/files_external_gdrive/pull/11 :)
