### ISSUE TITLE
Can't authorize my google account

### ISSUE THREAD

**Issue by dcrack** [NastuzziSamy/files_external_gdrive#22]
Error: redirect_uri_mismatch

Request Details
response_type=code
access_type=offline
client_id=*********167-q80q4273vphn5v0fl0ha************.apps.googleusercontent.com
redirect_uri=https://mywebsite.com/index.php/settings/admin/externalstorages
state=
scope=https://www.googleapis.com/auth/drive
approval_prompt=force

**Comment by Ryonez** [comment]
And the fix? @dcrack

**Comment by NastuzziSamy** [comment]
If you get this error, you have to change/add the right redirect url

**Comment by Ryonez** [comment]
I can read the error message, the issue I had was not knowing how to create a valid uri for this app. I figured it out though after digging through the issues here.

**Comment by thewillwilson** [comment]
Sorry to comment on this, but @Ryonez what is the correct valid uri?

**Comment by Ryonez** [comment]
@thewillwilson 

I honestly can't remember this atm. I looked at my google console though and I have these redirect URI's:
![image](https://user-images.githubusercontent.com/16157130/45592753-df41da00-b9c9-11e8-8afe-0b7fd0a0bf36.png)


Hopefully that helps.

**Comment by Ryonez** [comment]
You also need to enable the Drive API, if you haven't already.
