### ISSUE TITLE
Documentation please.

### ISSUE THREAD

**Issue by Ryonez** [NastuzziSamy/files_external_gdrive#23]
I'd like to see some actual documentation please. I had to poke in the issue to "find" the redirect url to use. Basically, you show how to install, but not how to set up.

I also wasted a lot of time before I noticed `Allow regular user to create its own Google Drive external storage` was unchecked in the todo list. Still not sure why that wouldn't work, but I was trying until then.

**Comment by bcutter** [comment]
Second that. Couldn´t manage to get things to work. Normal user needs to be able to embed the Google Drive. Will wait for the update which adds this feature, until then the app is useless for me personally. But I honour this work, please go on :-)

**Comment by dschrempf** [comment]
I found some [instructions](http://fuzzcast6.menoetius.feralhosting.com/bin/tobebined65464554366/nextcloud/core/doc/admin/configuration_files/external_storage/google.html) that worked for me. Not sure if this is official (I don't think so).

**Comment by NastuzziSamy** [comment]
Documentation is added. Normal user can now use GDrive (even if I still don't recommand it for now)
