### ISSUE TITLE
How do I install this if I installed nextcloud with snap

### ISSUE THREAD

**Issue by jeffli678** [NastuzziSamy/files_external_gdrive#24]
I wish to install this app because I do need support for google drive. However, I cannot make it. 

1. This app is not showing up in my app store.

2. I cannot install it manually. The snap file system is mounted read-only. I have no idea where to put the app folder. I tried to put it in the folder where other apps resdie, but since /snap is read-only and this is unseccessful. If I put it somewhere like ~, and execute "nextcloud.occ app:enable files_external_gdrive", it says cannot find files_external_gdrive

**Comment by NastuzziSamy** [comment]
Hi, check the README
