### ISSUE TITLE
OAuth2 Failure

### ISSUE THREAD

**Issue by sbrl** [NastuzziSamy/files_external_gdrive#25]
When I  try to use this, I get this in my browser when attempting to add the oauth client id + secret:

![image](https://user-images.githubusercontent.com/9929737/43993956-d918e7d0-9d8c-11e8-82e2-1c80b485eda0.png)

**Comment by helpsterTee** [comment]
You need to create your own OAuth2 client in the Google developer console:

- Go to https://console.developers.google.com/apis/credentials (create a new project, if you need to)
- Create an OAuth2-Client-ID
- Define the redirect URI to be https://yournextclouduri/index.php/settings/user/externalstorages
- You will get a client ID and secret that goes into the settings of files_external_gdrive

**attention: after adding the redirect URI, you need to press 'Save' twice!**

**Comment by sbrl** [comment]
Hey, thanks for the instructions @helpsterTee! It's now not showing that error and I can go through the whole process, but when I get back to my nextcloud instance, it doesn't appear to be picking it up:

![selection_062](https://user-images.githubusercontent.com/9929737/45184719-b1b59d80-b21f-11e8-947d-79ac331da985.png)

**Comment by llidd** [comment]
> Hey, thanks for the instructions @helpsterTee! It's now not showing that error and I can go through the whole process, but when I get back to my nextcloud instance, it doesn't appear to be picking it up:
> 
> ![selection_062](https://user-images.githubusercontent.com/9929737/45184719-b1b59d80-b21f-11e8-947d-79ac331da985.png)

did u handle this problem eventually?

**Comment by sbrl** [comment]
Nope. It still doesn't work @llidd. @helpsterTee, could you clear up any confusion here?

**Comment by helpsterTee** [comment]
Sorry I don't use this plugin anymore because I've migrated my stuff away from gdrive and performance was not that good. Maybe check logs for errors?

**Comment by sbrl** [comment]
Hrm. Nothing in the logs as far as I can tell. Maybe I'm looking in the wrong place.

**Comment by helpsterTee** [comment]
But it's showing the pop-up for your Google account to authorize the oauth application to access your files?

**Comment by sbrl** [comment]
Yep, @helpsterTee!

**Comment by NastuzziSamy** [comment]
Hi guys. I tryed to explain in the README how to make it work.
I also stabilize the code to be sure it works correctly.

I close this issue for now, let me know.
