### ISSUE TITLE
"Grant access" button not working

### ISSUE THREAD

**Issue by volker-fr** [NastuzziSamy/files_external_gdrive#28]
Now ticket for closed #4. Seems like there are two different issue while one got fixed.

Clicking the "Grant access" button doesn't do anything. Credentials etc. are double checked and ruled out as main issue.

The logfiles are empty. No hint here.

The developer console shows the following when I click on `Grant access`
* nextcloud/index.php/apps/files_external/ajax/oauth2.php is called and returns 200 and no data in the body is returned on that call. No additional call happens.
* Javascript error:
```
oauth2.js?v=bc9228a4-0:87 Uncaught TypeError: Cannot read property 'message' of undefined
    at Object.success (oauth2.js?v=bc9228a4-0:87)
    at j (core.js?v=bc9228a4-0:2)
    at Object.fireWith [as resolveWith] (core.js?v=bc9228a4-0:2)
    at x (core.js?v=bc9228a4-0:4)
    at XMLHttpRequest.<anonymous> (core.js?v=bc9228a4-0:4)
```

Additional, if I click on on the "Save" icon totally on the right the followin happens:

/nextcloud/apps/files_external/globalstorages is called with a POST. Payload is (order changed through json_pp):

```
{
   "testOnly" : true,
   "applicableUsers" : [],
   "mountPoint" : "GoogleDrive",
   "applicableGroups" : [],
   "backendOptions" : {
      "client_secret" : "YYYYY",
      "token" : "",
      "client_id" : "XXXXXXX",
      "configured" : ""
   },
   "priority" : 100,
   "mountOptions" : {
      "filesystem_check_changes" : 1,
      "previews" : true,
      "encrypt" : true,
      "enable_sharing" : false,
      "encoding_compatibility" : false
   },
   "authMechanism" : "oauth2::oauth2",
   "backend" : "files_external_gdrive"
}
```

This call returns  `422 Unprocessable Entity` with body
```
{"message":"Unsatisfied authentication mechanism parameters"}
```

Just looking at the call I am not sure what `"encrypt":true` means nor where it comes from. Server side encryption is disabled.

**Comment by towfiqi** [comment]
same here..

**Comment by NastuzziSamy** [comment]
Fixed on the next release

**Comment by diveyez** [comment]
> 
> 
> Fixed on the next release

No, it is not fixed. Sorry to disappoint.

**Comment by JamesDAdams** [comment]
Not fixed !
