### ISSUE TITLE
File downloads return JSON error as file content

### ISSUE THREAD

**Issue by simonbru** [NastuzziSamy/files_external_gdrive#3]
Downloading files seems to work, but I get the following as the file content:
```js
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "fileNotExportable",
    "message": "Export only supports Google Docs."
   }
  ],
  "code": 403,
  "message": "Export only supports Google Docs."
 }
}
```

This seems to happen with files that don't need conversion (such as zip or png files I just uploaded).
I get different results when downloading files created on Google Docs. Documents, sheets and drawings work fine. However with presentations I get a seemingly corrupted file, which libreoffice impress can repair and open after manually cutting the first bytes from the file.

**Nextcloud version:** 13.0.2 using the [13.0-apache docker image](https://hub.docker.com/_/nextcloud/)

**Comment by NastuzziSamy** [comment]
Hey, thanks for your feedback @simonbru 

It is fixed now in the v0.2.2 (available in the appstore) https://github.com/NastuzziSamy/files_external_gdrive/commit/1402013c30981180b4c882e87df463ce7a78521f
