### ISSUE TITLE
Does not work with Nextcloud 14

### ISSUE THREAD

**Issue by lazzurs** [NastuzziSamy/files_external_gdrive#30]
Hi,

I tried upgrading to Nextcloud 14 with this module installed and I was getting errors on unrelated modules. When I disabled this module suddenly the upgrade worked.

 After the upgrade I tried again to enable the module and got a stream of errors in the nextcloud.log which I can provide if required.

**Comment by r4sas** [comment]
Same problem. Related log:
```
PHP Fatal error:  Interface 'OCA\Files_External\Lib\Config\IBackendProvider' not found in /apps/files_external_gdrive/lib/AppInfo/Application.php on line 32
```
However, I disabled module and after that enabled files_external app.
After that all works.

**Comment by Golffies** [comment]
Similar issue here, with the very same error message. It got even worse, as it froze NextCloud. I had no way to remove the app through the command occ:disable, I must have to delete the ./apps/files_external_gdrive forlder to get back into control.

As a protective measure, the app should not be made available at all for NextCloud 14 in the app store.

**Comment by changchichung** [comment]
same here , and I cant disable that app , and can not download and enable any other apps now ..

**Comment by livier** [comment]
+1
On activation I get ; 
Client error: `GET https://cloud.nastuzzi.fr/s/Da2XHGEJfq3SEWr/download` resulted in a `404 Not Found` response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found (truncated...)

**Comment by jcklpe** [comment]
Same here. New installation is impossible. Following the download link results in a 404. It seems the link is dead?

Same result for the files-right-click app which is also made by @NastuzziSamy (many thanks to you for such a necessary UX improvement!)

It seems that there is perhaps something broken with his cloud or something else of the sort? I imagine that a manual installation would work though?

**Comment by jcklpe** [comment]
Ah here's an answer to the issue: https://github.com/NastuzziSamy/files_rightclick/issues/30

**Comment by BudSun** [comment]
> +1
> On activation I get ;
> Client error: `GET https://cloud.nastuzzi.fr/s/Da2XHGEJfq3SEWr/download` resulted in a `404 Not Found` response: <title>404 Not Found</title>
> 
> # Not Found (truncated...)
I solved it by following the steps below.
From git
First, clone the repo git clone https://github.com/NastuzziSamy/files_external_gdrive.git
Execute make install in the app directory
And enable the app with php occ app:enable files_external_gdrive in the Nextcloud directory

**Comment by NastuzziSamy** [comment]
Hey guys, sorry for this, as I said here: https://github.com/NastuzziSamy/files_rightclick/issues/30#issuecomment-434241388 I uploaded my cloud with the next version of NC and Pretty urls were not working anymore..

Enjoy, it is up now, but be carefull with this package, still in beta and unstable
