### ISSUE TITLE
download is down...

### ISSUE THREAD

**Issue by av1312** [NastuzziSamy/files_external_gdrive#32]

**Comment by av1312** [comment]
there is the following error 

cURL error 7: Failed to connect to cloud.nastuzzi.fr port 443: No route to host (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

any ideas

**Comment by nliautaud** [comment]
Same issue.

Would it be possible to point the plugins to the Github repos `/releases/latest` to avoid the downtimes ?

Related : 
- #9 
- #10 
- https://github.com/NastuzziSamy/files_external_gdrive/issues/30#issuecomment-431712024 
- https://github.com/NastuzziSamy/files_rightclick/issues/31
- https://github.com/NastuzziSamy/files_rightclick/issues/30
- https://github.com/NastuzziSamy/files_rightclick/issues/25
- https://github.com/NastuzziSamy/files_rightclick/issues/3

**Comment by NastuzziSamy** [comment]
Fixed, I'll release a new version soon on a different plateform
