### ISSUE TITLE
HTTP ERROR 500 after installation of the App!

### ISSUE THREAD

**Issue by messalas** [NastuzziSamy/files_external_gdrive#33]
I tried to install it from the apps in the admin page and after the installation the page was showing:

> This page isn’t working
> page is currently unable to handle this request.
> 
> HTTP ERROR 500
and in the Apache log I got the following:

`PHP Fatal error: Interface 'OCA\\Files_External\\Lib\\Config\\IBackendProvider' not found in /var/www/html/scti.gr/mycloud/apps/files_external_gdrive/lib/AppInfo/Application.php on line 32`

Is this a bug or I was supposed to install sth else first?

_Nextcloud version : 14.0.3
Operating system and version: Ubuntu 16.04
Apache : Apache/2.4.18 (Ubuntu)
PHP version : PHP 7.0.32-0ubuntu0.16.04.1_

**Comment by TravisNoles** [comment]
I get the same error, it completely breaks the install of Nextcloud. The only way that I know of to fix it, is to remove the app.

**Comment by MLutt** [comment]
Same here, was lucky enough to have the page to remove the app cached - it trashpiled my installation and I had to do a clean reinstall...

**Comment by wjhill** [comment]
I am another one who installed yesterday and ran into this issue (Nextcloud 14.0.4 on UnRaid 6.6.6 [I know!] via the LinuxServer.io Docker).

I followed the information at a [NextCloud forms post](https://help.nextcloud.com/t/google-drive-external-files-0-2-8-app-suspected-of-involvement-in-my-php-fatal-error-sev-1/32494) on this to resolve. I did follow-up by rebooting, going into the Apps section in my NextCloud instance, and hitting the "Disable" on this plugin.

**Comment by nshaud** [comment]
This error happens when you activate `files_external_gdrive` *without* `files_external`, which it apparently requires.

FYI, you can salvage without reinstalling by switching "yes" to "no"for `files_external_gdrive` in the Nextcloud SQL table "appconfig".

**Comment by BUG-reporter** [comment]
The same shit. Two times it broke my Nextcloud. Thanks to Btrfs snapshots of my systemd-container. They saved my time. No plugin should break Nextcloud, even if it depends on another plugin or requires something else. This is not normal. It should be removed from NextCloud AppStore definitely.

**Comment by NastuzziSamy** [comment]
> The same shit. Two times it broke my Nextcloud. Thanks to Btrfs snapshots of my systemd-container. They saved my time. No plugin should break Nextcloud, even if it depends on another plugin or requires something else. This is not normal. It should be removed from NextCloud AppStore definitely.

I think I have to go straight with you @BUG-reporter :
- Insults are not welcomed here or on any github repos,
- Why commenting a known issue with an unknown account ? Can't you use yours ?
- I am sorry for the breackages, I know how it feels,
- As it is said on the title of the repo, it is "UNSTABLE" and on "BETA", I can't aware more than that,
- As we are in an OpenSource community, don't you think you should at least check the repo, the README and (should check) the code ?
- For Nextcloud, I agree with you, an app should not break an instance. Unfortunatly, I can't disable/remove an app from the AppStore.

For the others, I am ending working on another app; I will release a new version (which breaks nothing I hope) at the end of the month.

**Comment by BUG-reporter** [comment]
> > The same shit. Two times it broke my Nextcloud. Thanks to Btrfs snapshots of my systemd-container. They saved my time. No plugin should break Nextcloud, even if it depends on another plugin or requires something else. This is not normal. It should be removed from NextCloud AppStore definitely.
> 
> I think I have to go straight with you @BUG-reporter :
> 
> * Insults are not welcomed here or on any github repos,

Well, who's been insulted?

> * Why commenting a known issue with an unknown account ? Can't you use yours ?
What does it mean" "unknown account"? This is my account with my nickname.

> * I am sorry for the breackages, I know how it feels,
> * As it is said on the title of the repo, it is "UNSTABLE" and on "BETA", I can't aware more than that,
> * As we are in an OpenSource community, don't you think you should at least check the repo, the README and (should check) the code ?

A can't check the code of all apps I'm using with NextCloud. Sorry, I have not so much time to analyze the code of all apps I am using.

> * For Nextcloud, I agree with you, an app should not break an instance. Unfortunatly, I can't disable/remove an app from the AppStore.
Ok.

**Comment by fenvarien** [comment]
Thank you, NastuzziSamy for your hard work! I'm really looking forward for a new version of this much needed app.

**Comment by NastuzziSamy** [comment]
@fenvarien, thank you, it is kind :)

So you know, I am doing an internship (I am commenting this issue during my work time but shhhhh) and I already have projects that take all the rest of my time. But I will try to publish a release, at the end of the month, if I find some time ;)

**Comment by NastuzziSamy** [comment]
Here I am, i am releasing a new update, after closing a maximum of issues, stay tuned
