### ISSUE TITLE
Can't Download from apps store

### ISSUE THREAD

**Issue by Simon808** [NastuzziSamy/files_external_gdrive#36]
Hello, Your server is down?
I can't download it from your server .....
May you open again ?It is a great plug in for me^^ thx

From my log:
cURL error 7: Failed to connect to cloud.nastuzzi.fr port 443: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by Aterfax** [comment]
Same here.

**Comment by NastuzziSamy** [comment]
Hi, fixed ;)
