### ISSUE TITLE
Grant access not working

### ISSUE THREAD

**Issue by joekerna** [NastuzziSamy/files_external_gdrive#4]
I've created the Google Drive API app and entered my credentials (Client ID, Secret Key) into the external storage settings.
When I click on `grant access` nothing happens.
This happens with Firefox and Edge on Windows 10 and app version 0.2.5

**Comment by Ra72xx** [comment]
Same with openSUSE 15.0 and Firefox.

**Comment by NastuzziSamy** [comment]
Hi, thanks, it is fixed now: https://github.com/NastuzziSamy/files_external_gdrive/commit/c7aecb198eb9ba4fb52d2b2aba96522be5a9c907

I will release a new version when i will correct an other bug ;)

**Comment by brzd** [comment]
Hi, just had time to install this during the weekend, but wasn't able to integrate gdrive. 

Should it work with 2 step verification on?

Brzd

**Comment by joekerna** [comment]
With 2.6 `grant access` leads to a Google Error 500 website
![grafik](https://user-images.githubusercontent.com/23077594/40531647-3b2568cc-5ffd-11e8-9e6a-6e8fe7e3e9cd.png)

I've double checked my client-id and secrey key. Is there anything else I could be missing?

**Comment by joekerna** [comment]
After logging out and into my Google account it's redirecting to the authorization page now.

**Comment by NastuzziSamy** [comment]
@joekerna I tried again to connect, and I did not have any issues.

Did you:
- Checked your client id/secret key by inspecting the json sent ?
- Gave the right callback url in the Google console ?
- Succeeded to grant access before 0.2.6 ?

**Comment by joekerna** [comment]
I've managed to add the storage to my file list. But once I click on it, it says

> Storage is temporarily not available (Translated from German)

The log says:

> Sabre\DAV\Exception\ServiceUnavailable: Storage is temporarily not available
/var/www/nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/LockPlugin.php - line 144:  OCA\DAV\Connector\Sabre\ObjectTree->getNodeForPath('googledrive')
/var/www/nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/LockPlugin.php - line 114:  OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->getNode('googledrive', 'PROPFIND')
[internal function] OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkLock(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:  call_user_func_array(Array, Array)
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466:  Sabre\Event\EventEmitter->emit('beforeMethod', Array)
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:  Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80:  Sabre\DAV\Server->exec()
/var/www/nextcloud/remote.php - line 164:  require_once('/var/www/nextcl...')
{main}

Is there anything I can provide to further debug? Is this a new issue?

**Comment by joekerna** [comment]
It's working with version 2.8.

Thanks a lot

**Comment by NastuzziSamy** [comment]
@jokerna No worries, it is thanks to you ;)

**Comment by SGatBugs** [comment]
Unfortunately granting access is not working for me with version 0.2.8 in nextcloud 13.0.2 on Univention Corporate Server 4.3. I have also uninstalled and reinstalled nextcloud without effect.
Has anyone else still this issue? What information do you need for debugging?

**Comment by LawnSounds** [comment]
Have you tried logging out and back in @SGatBugs ?

**Comment by SGatBugs** [comment]
Do you mean logging out and back in into the google account? I have tried this without any effect. Pushing the grant access button has no effect. Of course Client-ID and Secret are filled in.
