### ISSUE TITLE
v 0.2.6 not upgrading through nc-appstore

### ISSUE THREAD

**Issue by JimmyKater** [NastuzziSamy/files_external_gdrive#6]
latest version 0.2.5 doesnt show that there is an update available in NC-appstore

**Comment by NastuzziSamy** [comment]
Hey, it is intentional, the 0.2.6 is not fully working, like said here: https://github.com/NastuzziSamy/files_external_gdrive/issues/5

**Comment by JimmyKater** [comment]
oops. sorry. i read that and thought after a while that you might have solved the issue(s) in the meanwhile. my mistake ...

**Comment by NastuzziSamy** [comment]
Haha @JimmyKater no worries, it is alright, it happens :p

**Comment by NastuzziSamy** [comment]
@JimmyKater just you to know, it is fixed ;)
