### ISSUE TITLE
NC 20 Support?

### ISSUE THREAD

**Issue by ghost** [NastuzziSamy/files_external_gdrive#61]
Nextcloud 20 Support?

**Comment by retiolus** [comment]
I don't think so, I've just installed and "Grant access" button doesn't work.

**Comment by useventsllc** [comment]
same

**Comment by ghost** [comment]
I am asking when will there be NC 20 support?

**Comment by ghost** [comment]
I think that this repo is dead? There has been no change for over a year

**Comment by hmlendea** [comment]
Seems dead

**Comment by ghost** [comment]
Sorry wrong button. but now onto NC 21

**Comment by NastuzziSamy** [comment]
https://github.com/NastuzziSamy/files_external_gdrive/issues/63
