### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ww1425680101** [NastuzziSamy/files_external_gdrive#8]
Undefined property: OCA\Files_external_gdrive\Storage\Adapter::$fetchfieldsGet at /usr/local/caddy/www/nextcloud/apps/files_external_gdrive/lib/Storage/Adapter.php#156

Wrong information

External storage support for Google Drive V0.2.7

**Comment by NastuzziSamy** [comment]
Thx, it is fixed now: https://github.com/NastuzziSamy/files_external_gdrive/commit/6bb6795704e49df0ed90ee46ce1b1c5fbcd9e505
